name: Icons
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  jobs:
    github-metrics:
      runs-on: ubuntu-latest
  steps:
    - uses: lowlighter/metrics@latest
        with:
        filename: metrics.plugin.topics.icons.svg
        token: NOT_NEEDED
        base: ""
        plugin_topics: yes
        plugin_topics_limit: 0
        plugin_topics_mode: icons
